### ISSUE TITLE
set up fragments to be added to the motd

### ISSUE THREAD

**Issue by jjolet** [fvoges/puppet-motd#1]
I'm using roles and profiles and i'm trying to figure out what the syntax is (and where can i put the statements) to actually add fragments to the motd.  Do you have some examples on how to get data used by the fragments.pp?

**Comment by fvoges** [comment]
The main class would be used on your base/common/global profile and then you use motd::fragment on other profiles to add stuff to the MOTD file.

I've added some more documentation to the README and pushed a new version to the Forge.
